main: com.Stranded.Main
version: 1.12
name: Stranded
authors: [The_Spaceman, 7h3_4rch3r]

commands:
  nexus:
    description: summon a nexus
  edit:
    description: test
  war:
    description: start a war
  island:
    description: island
    aliases: [i]
  warisland:
    description: war islands
  tower:
    description: get your towers
  gamble:
    description: gamble bitch
  stranded:
    description: main server command
  chat:
    description: chat with your island members
  loottable:
    description: deal with lootTables
  chatfilter:
    description: customize chat with filters
  reply:
    description: reply to other people
  trade:
    description: feautere not available yet
  map:
    description: add custom maps to your world (ex. preview of warIslands)
  towerteleport:
    description: teleport to players who are within the range of the telport tower
    aliases: [twtp]